version: '3'
services:
  server:
    build: server
    ports:
      - "8080:8080"
  client:
    build: client
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
